# Generated by Django 5.2.8 on 2025-12-01 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('udemy_app', '0003_cart_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name_en',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='full_name_ru',
        ),
    ]
